baseURL = 'https://ppsteven.github.io/github-style-blog/'
locale = 'en-us'
title = 'PPSteven Blog'
theme = 'github-style'

[params]
  author = "PPSteven"
  description = "A blog about technology, coding and more"
  github = "PPsteven"
  avatar = "https://github.com/PPsteven.png"
  url = "https://ppsteven.github.io"
  headerIcon = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
