baseURL = 'https://ppsteven.github.io/github-style-blog/'
locale = 'en-us'
title = 'PPSteven Blog'
theme = 'github-style'

[params]
  author = "PPSteven"
  description = "A blog about technology, coding and more"
